'use strict';

// GET /api/brand — the front-page content: the visual register (the 5
// brand-guidelines markdown docs) + a curated set of vault voice/positioning
// notes (external-audience only). Rendered to HTML server-side via marked.

const express = require('express');
const fs = require('fs');
const path = require('path');
const { marked } = require('marked');
const db = require('../db');
const { dirs } = require('../lib/storage');

const r = express.Router();

// Order the guideline docs by their numeric filename prefix (00, 01, ...).
function readGuidelines() {
  const gdir = path.join(dirs().library, 'brand-guidelines');
  let files = [];
  try { files = fs.readdirSync(gdir).filter((f) => f.toLowerCase().endsWith('.md')); } catch { return []; }
  files.sort();
  return files.map((f) => {
    let raw = fs.readFileSync(path.join(gdir, f), 'utf8');
    raw = raw.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/, ''); // strip YAML frontmatter
    const title = f.replace(/\.md$/i, '').replace(/^\d+\s*[—-]\s*/, '');
    return { file: f, title, html: marked.parse(raw) };
  });
}

// ── Published brand canon (compiled from vault by /brand-sync) ──────────────
// The cache is a published snapshot with provenance; the authoring home is the
// vault (manifest: "Brand Thinking — Hub"). See STUDIO-PRD.md.

const KIND_LABELS = {
  voice: 'Voice', style: 'Style mechanics', lexicon: 'Lexicon',
  format: 'Format by funnel stage', register: 'Visual register',
  routing: 'Routing', principle: 'Principles',
};
const KIND_ORDER = ['voice', 'style', 'lexicon', 'format', 'register', 'principle', 'routing'];

function renderAmbient(rules) {
  const compiled = rules[0]?.compiled_at ? rules[0].compiled_at.slice(0, 10) : 'never';
  const lines = [
    '# Fresh Context - ambient brand rules',
    '',
    `> GENERATED by /brand-sync - do not hand-edit. Compiled ${compiled} from the vault's [[Brand Thinking - Hub]] compile sources (⚙). ${rules.length} always-apply rules. Regenerate: \`node brand-studio/scripts/render-ambient.js\` after a publish.`,
    '',
  ];
  for (const kind of KIND_ORDER) {
    const group = rules.filter((x) => x.kind === kind);
    if (!group.length) continue;
    lines.push(`## ${KIND_LABELS[kind] || kind}`, '');
    for (const x of group) lines.push(`- ${x.rule}`);
    lines.push('');
  }
  return lines.join('\n');
}

// GET /api/brand/rules?scope=tof|mof|bof&kind=&ambient=true — situational reads
// (the MCP tone-for-stage door). scope queries include the globals.
r.get('/rules', async (req, res) => {
  try {
    const rules = await db.listBrandRules({
      scope: req.query.scope || null,
      kind: req.query.kind || null,
      ambient: req.query.ambient != null ? req.query.ambient === 'true' : null,
      audience: req.query.audience || null,
    });
    res.json(rules);
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// GET /api/brand/ambient — the compiled always-apply fragment as markdown.
// Renders live from the same rows the committed brand/ambient.md is rendered
// from; the endpoint exists for cloud agents that can't read the repo file.
r.get('/ambient', async (_req, res) => {
  try {
    const rules = await db.listBrandRules({ ambient: true, audience: 'external' });
    res.type('text/markdown').send(renderAmbient(rules));
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// POST /api/brand/publish { rules: [...] } — replace-all publish from
// /brand-sync (bearer-gated like all of /api). The publish step is reviewed
// by a human before this call is made.
r.post('/publish', async (req, res) => {
  try {
    const rules = req.body?.rules;
    if (!Array.isArray(rules) || !rules.length) return res.status(400).json({ error: 'rules[] required' });
    for (const x of rules) {
      if (!x.kind || !x.rule) return res.status(400).json({ error: 'each rule needs kind + rule' });
    }
    const written = await db.replaceBrandRules(rules);
    res.json({ published: written.length, compiled_at: written[0]?.compiled_at });
  } catch (e) { res.status(500).json({ error: e.message }); }
});

r.get('/', async (_req, res) => {
  try {
    const guidelines = readGuidelines();
    let voice = [];
    try {
      const notes = await db.brandVoiceNotes(8);
      voice = notes.map((n) => ({
        title: n.title,
        html: marked.parse((n.body_md || '').slice(0, 2000)),
      }));
    } catch { /* vault notes optional */ }
    let rules = [];
    try { rules = await db.listBrandRules({}); } catch { /* pre-publish: table may be empty */ }
    res.json({ rules, guidelines, voice });
  } catch (e) { res.status(500).json({ error: e.message }); }
});

module.exports = r;
